Repository apache/ambari-infra, pull requests merged in 2018-10, with the labels that each got.

#1 AMBARI-24721. Use maven docker plugin to build infra solr images
  .gitignore
  Makefile
  ambari-infra-assembly/pom.xml
  ambari-infra-manager-it/pom.xml
  jenkins/containers/docker-infra-solr/Dockerfile
  jenkins/containers/docker-infra-solr/bin/entrypoint.sh
  jenkins/containers/docker-infra-solr/bin/init.sh
  jenkins/containers/docker-infra-solr/conf/infra-solr.conf
  jenkins/containers/docker-infra-solr/conf/solr.xml
  pom.xml
Labels: enhancement

#2 AMBARI-24725 - Infra Solr: manage autoscaling properties in Ambari
  ambari-infra-solr-client/src/main/java/org/apache/ambari/infra/solr/AmbariSolrCloudCLI.java
  ambari-infra-solr-client/src/main/java/org/apache/ambari/infra/solr/AmbariSolrCloudClient.java
  ambari-infra-solr-client/src/main/java/org/apache/ambari/infra/solr/AmbariSolrCloudClientBuilder.java
  ambari-infra-solr-client/src/main/java/org/apache/ambari/infra/solr/commands/SetAutoScalingZkCommand.java
  ambari-infra-solr-client/src/main/java/org/apache/ambari/infra/solr/domain/ZookeeperClient.java
Labels: enhancement

#3 AMBARI-24746. Upgrade Solr version to 7.5.0
  ambari-infra-manager/docker/docker-compose.yml
  ambari-infra-manager/docker/infra-manager-docker-compose.sh
  ambari-infra-solr-client/README.md
  ambari-infra-solr-client/src/main/python/migrationHelper.py
  ambari-infra-solr-client/src/main/resources/solrIndexHelper.sh
  ambari-infra-solr-plugin/docker/infra-solr-docker-compose.sh
  pom.xml
Labels: enhancement

#6 AMBARI-24761 - Infra Manager: hive support for archiving Infra Solr
  ambari-infra-manager-it/src/test/resources/stories/infra_api_tests.story
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/job/archive/BZip2Compressor.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/job/archive/Document.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/job/archive/DocumentArchivingConfiguration.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/job/archive/FileNameSuffixFormatter.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/job/archive/SolrDocumentIterator.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/job/archive/SolrParametrizedString.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/job/archive/SolrQueryBuilder.java
  ambari-infra-manager/src/main/resources/infra-manager.properties
  ambari-infra-manager/src/test/java/org/apache/ambari/infra/job/archive/DocumentExporterTest.java
  ambari-infra-manager/src/test/java/org/apache/ambari/infra/job/archive/DocumentItemReaderTest.java
  ambari-infra-manager/src/test/java/org/apache/ambari/infra/job/archive/FileNameSuffixFormatterTest.java
  ambari-infra-manager/src/test/java/org/apache/ambari/infra/job/archive/LocalDocumentItemWriterTest.java
  ambari-infra-manager/src/test/java/org/apache/ambari/infra/job/archive/SolrParametrizedStringTest.java
  ambari-infra-manager/src/test/java/org/apache/ambari/infra/job/archive/SolrQueryBuilderTest.java
Labels: enhancement

#7 AMBARI-24777 - Infra Manager: Remove dependencies due to security concerns.
  ambari-infra-manager-it/src/test/java/org/apache/ambari/infra/steps/AbstractInfraSteps.java
  ambari-infra-manager-it/src/test/resources/stories/infra_api_tests.story
  ambari-infra-manager/pom.xml
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/InfraManager.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/conf/InfraManagerJerseyResourceConfig.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/conf/InfraManagerServletConfig.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/conf/InfraManagerWebServerCustomizer.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/doc/InfraManagerApiDocStorage.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/rest/JobResource.java
  ambari-infra-manager/src/main/resources/infra-manager-env.sh
  ambari-infra-manager/src/main/resources/swagger/swagger.html
  pom.xml
Labels: security

#9 AMBARI-24807 - Infra Manager: unable to restart job
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/job/JobScheduler.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/manager/JobManager.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/manager/Jobs.java
  ambari-infra-manager/src/main/resources/infra-manager.properties
  ambari-infra-manager/src/test/java/org/apache/ambari/infra/job/JobSchedulerTest.java
Labels: bug

#13 AMBARI-24807 - ADDENDUM Infra Manager: unable to restart job
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/job/JobScheduler.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/manager/JobManager.java
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/manager/Jobs.java
  ambari-infra-manager/src/test/java/org/apache/ambari/infra/job/JobSchedulerTest.java
Labels: bug

#12 AMBARI-24838 - Infra Manager: zookeper connection string
  ambari-infra-manager/src/main/java/org/apache/ambari/infra/job/SolrDAOBase.java
Labels: bug
